apiVersion: apps/v1
kind: Deployment
metadata:
  name: investing-scraper-deploy
spec:
  selector:
    matchLabels:
      app: investing-scraper    
  minReadySeconds: 5
  template:               
    metadata:
      labels:
        app: investing-scraper  
    spec:                
      nodeSelector:
        kubernetes.io/hostname: team5-vm-3
      containers:
      - name: investing-scraper
        image: 129.114.25.102:5000/my-scraper
        imagePullPolicy: Always  
        env:
        - name: CLIENT_ID
          value: -2Ug3EBM12gxLw
        - name: CLIENT_SECRET
          value: VidkxqeN0hOwsaIIPrSU3h9caVLLwg
        - name: SUBREDDIT
          value: investing
        command: ["python3"]
        args: ["/stream_reddit.py"] 
      restartPolicy: Always  
