# This is a declarative approach to describe a Job type Kubernetes
# workload.   Since this is YAML, the indentation is very important
apiVersion: apps/v1
kind: Deployment         # We are testing the Job resource type
metadata:
  name: rstocks-scraper-deploy  # A name must be given to the Job type in the metadata section
spec:
  selector:
    matchLabels:
      app: rstocks-scraper          # Basically this is like the search string used to locate the pods
  minReadySeconds: 5
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: rstocks-scraper        # some label to give to this pod (see the matching label above)
    spec:                 # actual specification
      nodeSelector:
        kubernetes.io/hostname: kubemaster
      containers:
      - name: rstocks-scraper       # this is going to be used for DNS name
        # Change the IP address to where you are running this
        image: 129.114.25.102:5000/my-scraper   # this is the image in registry accessible
        imagePullPolicy: Always  # This forces the node to pull the image
        env:
        - name: CLIENT_ID
          value: -2Ug3EBM12gxLw
        - name: CLIENT_SECRET
          value: VidkxqeN0hOwsaIIPrSU3h9caVLLwg
        - name: SUBREDDIT
          value: stocks
        command: ["python3"]
        args: ["/stream_reddit.py"]  # arguments to run. I am running this for 1000
                                                                                                       # iterations so that we have time to do an exec
                                                                                                       # and open a shell to the running pod
      restartPolicy: Always  # we ask Kubernetes not to restart
 
