apiVersion: apps/v1
kind: Deployment        
metadata:
  name: rstocks-scraper-deploy  
spec:
  selector:
    matchLabels:
      app: rstocks-scraper         
  minReadySeconds: 5
  template:             
    metadata:
      labels:
        app: rstocks-scraper  
    spec:                 
      nodeSelector:
        kubernetes.io/hostname: kubemaster
      containers:
      - name: rstocks-scraper
        image: 129.114.25.102:5000/my-scraper
        imagePullPolicy: Always  # This forces the node to pull the image
        env:
        - name: CLIENT_ID
          value: -2Ug3EBM12gxLw
        - name: CLIENT_SECRET
          value: VidkxqeN0hOwsaIIPrSU3h9caVLLwg
        - name: SUBREDDIT
          value: stocks
        command: ["python3"]
        args: ["/stream_reddit.py"] 
      restartPolicy: Always  
 
