apiVersion: apps/v1
kind: Deployment         
metadata:
  name: wsb-scraper-deploy  
spec:
  selector:
    matchLabels:
      app: wsb-scraper          
  minReadySeconds: 5
  template:               
    metadata:
      labels:
        app: wsb-scraper        
    spec:                 
      nodeSelector:
        kubernetes.io/hostname: kubemaster
      containers:
      - name: wsb-scraper   
        image: 129.114.25.102:5000/my-scraper   # this is the image in registry accessible
        imagePullPolicy: Always  # This forces the node to pull the image
        env:
        - name: CLIENT_ID
          value: -2Ug3EBM12gxLw
        - name: CLIENT_SECRET
          value: VidkxqeN0hOwsaIIPrSU3h9caVLLwg
        - name: SUBREDDIT
          value: wallstreetbets
        command: ["python3"]
        args: ["/stream_reddit.py"]  
      restartPolicy: Always  # we ask Kubernetes not to restart
 
